### ISSUE TITLE
Fatal error in Twitter connector

### ISSUE THREAD

**Issue by jsilvestre** [cozy-labs/konnectors#111]
I tried to import my tweets this morning, and it didn't work. The application crashed, and then restarted. Here are the logs:
```
[2015-07-31 09:13:25:118] info  - Twitter | Import started
[Fri, 31 Jul 2015 09:13:25 GMT] - GET /konnectors/e2f72c6a145ac9cc43e3429cb811e5d0 - 200 - 8.806 ms -  626
[Fri, 31 Jul 2015 09:13:25 GMT] - GET /konnectors/e2f72c6a145ac9cc43e3429cb811e5d0 - 200 - 11.940 ms -  626
[Fri, 31 Jul 2015 09:13:25 GMT] - GET /konnectors/e2f72c6a145ac9cc43e3429cb811e5d0 - 200 - 27.462 ms -  626
/usr/local/cozy/apps/konnectors/build/server/konnectors/twitter.js:91

    if ((tweets.length != null) && tweets.length > 0) {
               ^

TypeError: Cannot read property 'length' of undefined
    at /usr/local/cozy/apps/konnectors/build/server/konnectors/twitter.js:91:16
    at /usr/local/cozy/apps/konnectors/node_modules/cozydb/lib/model.js:198:20
    at /usr/local/cozy/apps/konnectors/node_modules/cozydb/lib/cozymodel.js:250:18
    at ClientRequest.<anonymous> (/usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/request-json-light/main.js:103:12)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketOnEnd [as onend] (http.js:1573:9)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

It's worth to mention that I then try again, and it worked. So apparently it only concerns the initial import.

**Comment by frankrousseau** [comment]
Can you update the application and try again before we release it?

**Comment by frankrousseau** [comment]
I close that one because I don't have any news from the bug reporter. @jsilvestre feel free to open it again if needed.
