### ISSUE TITLE
Error: konnectors CANT START at onExit spawner.js:119:25

### ISSUE THREAD

**Issue by nical** [cozy-labs/konnectors#121]
I get this error when installing  Konnectors on my cozy (On a debian at hosted at DigitalOcean):

```
konnectors CANT START : Error: konnectors CANT START at onExit (/usr/local/lib/node_modules/cozy-controller/build/server/lib/spawner.js:119:25) at listener (/usr/local/lib/node_modules/cozy-controller/node_modules/forever-monitor/node_modules/broadway/node_modules/eventemitter2/lib/eventemitter2.js:251:10) at EventEmitter.emit (/usr/local/lib/node_modules/cozy-controller/node_modules/forever-monitor/node_modules/broadway/node_modules/eventemitter2/lib/eventemitter2.js:339:22) at letChildDie (/usr/local/lib/node_modules/cozy-controller/node_modules/forever-monitor/lib/forever-monitor/monitor.js:172:12) at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cozy-controller/node_modules/forever-monitor/lib/forever-monitor/monitor.js:186:7) at ChildProcess.emit (events.js:98:17) at Process.ChildProcess._handle.onexit (child_process.js:809:12)
```
I tried to uninstall and re-install konnectors, but I am running into the same error.

**Comment by nical** [comment]
Actually, looks like a missing node dependency: I see this in the app's log
```
module.js:340
    throw err;
          ^
Error: Cannot find module 'americano'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/cozy/apps/konnectors/build/server.js:4:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by ZeHiro** [comment]
Hey, you can try to do type these commands as root: 

npm install && cd client & npm install && cd .. & cake build

**Comment by frankrousseau** [comment]
Are you sure you have enough disk space and ram available?

**Comment by nical** [comment]
(late answer, sorry) looks like RAM was the issue. I stopped all my cozy apps and konnector installed successfully.

**Comment by frankrousseau** [comment]
Ok great. Thank you for the report!
