### ISSUE TITLE
Numéricable's konnector not working anymore

### ISSUE THREAD

**Issue by nicofrand** [cozy-labs/konnectors#193]
The last commits broke the konnector.

0. The [lint commit](https://github.com/cozy-labs/konnectors/commit/61bf673c7916393a67d6dbe687cf4bfef84488d9) introduced french variables, I am not a big fan, I'd prefer english words.
0. A [merge commit](https://github.com/cozy-labs/konnectors/commit/723cd1b91c1ec5e0baff0c64411fa007c5de8a26#diff-ebf3d2e13976d197b3c88bcbfd7397ccL69) introducing conflicts was published but the variables names differ from one line to another (`connection` used instead of `connexionUrl`).
0. After this merge, a [fix](https://github.com/cozy-labs/konnectors/commit/43078bd406d2268dd80dfb2ebb3a04ed4c00fc1b#diff-ebf3d2e13976d197b3c88bcbfd7397ccL71) appeared without fixing the variables names issue

Could we just go back to the state before [the first commit](https://github.com/cozy-labs/konnectors/commit/723cd1b91c1ec5e0baff0c64411fa007c5de8a26) please ? I'll lint the konnector later if needed.

Error in the logs:

```
[Wed, 10 Feb 2016 13:22:26 GMT] - GET /konnectors/68083fef7ad3d9ac36ab3ba41310c7fd - 200 - 31.703 ms -  504
[2016-02-10 14:22:26:483] info - numericable | Import started
[2016-02-10 14:22:26:485] info - numericable | Import finished
[Wed, 10 Feb 2016 13:22:26 GMT] - GET /konnectors/68083fef7ad3d9ac36ab3ba41310c7fd - 200 - 28.391 ms -  503
error - konnector controller | ReferenceError: connection is not defined
    at Ware.logIn (/usr/local/cozy/apps/konnectors/build/server/konnectors/numericable.js:83:18)
    at Ware.<anonymous> (/usr/local/cozy/apps/konnectors/node_modules/ware/node_modules/wrap-fn/index.js:45:19)
    at next (/usr/local/cozy/apps/konnectors/node_modules/ware/lib/index.js:85:20)
    at Ware.run (/usr/local/cozy/apps/konnectors/node_modules/ware/lib/index.js:88:3)
    at Fetcher.fetch (/usr/local/cozy/apps/konnectors/build/server/lib/fetcher.js:25:26)
    at Object.module.exports.fetch (/usr/local/cozy/apps/konnectors/build/server/konnectors/numericable.js:52:38)
    at /usr/local/cozy/apps/konnectors/build/server/models/konnector.js:136:32
    at /usr/local/cozy/apps/konnectors/node_modules/cozydb/lib/model.js:40:14
    at /usr/local/cozy/apps/konnectors/node_modules/cozydb/lib/cozymodel.js:114:18
    at parseBody (/usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
```

**Comment by clochix** [comment]
Thanks for reporting @nicofrand,
Seems like the [lint commit](https://github.com/cozy-labs/konnectors/commit/61bf673c7916393a67d6dbe687cf4bfef84488d9#diff-ebf3d2e13976d197b3c88bcbfd7397cc) from @Peltoche was right, but we failed properly resolve conflicts when merging.
@frankrousseau could you have a look at this, please ?

@nicofrand waiting for the fix, maybe you can locally check out the last working commit?

**Comment by frankrousseau** [comment]
@nicofrand I think it's better if you handle the renaming yourself. We'll be sure that it's ok with your code styling.

Sorry for this ugly merge.
