### ISSUE TITLE
Exception in ISEN Konnector

### ISSUE THREAD

**Issue by clochix** [cozy-labs/konnectors#203]
Konnectors refuse to start because the parameters of the ISEN konnector are wrong:
```
/usr/local/cozy/apps/konnectors/build/server/konnectors/isen.js:112
    ref = requiredFields.email.split('@'), firstPart = ref[0], secondPart = re
                               ^
TypeError: Cannot call method 'split' of undefined
    at Object.module.exports.fetchIcs (/usr/local/cozy/apps/konnectors/build/server/konnectors/isen.js:112:32)
    at async.waterfall.notifContent (/usr/local/cozy/apps/konnectors/build/server/konnectors/isen.js:63:24)
    at fn (/usr/local/cozy/apps/konnectors/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/local/cozy/apps/konnectors/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:363:15)
```

**Comment by frankrousseau** [comment]
Thx @clochix
