### ISSUE TITLE
Capitaine train fails on daily fetch

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#360]
here is the error : 
```
[2016-07-14 08:24:25:495] info - Ical Feed | Downloading ICS file...
/usr/local/cozy/apps/konnectors/build/server/konnectors/captain_train.js:74
    var cookie = res.headers['set-cookie'][0];
                                          ^

TypeError: Cannot read property '0' of undefined
    at Request._callback (/usr/local/cozy/apps/konnectors/build/server/konnectors/captain_train.js:74:43)
    at Request.self.callback (/usr/local/cozy/apps/konnectors/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/cozy/apps/konnectors/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/konnectors/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

A disconnection should be added at the end.

**Comment by ZeHiro** [comment]
This could also be an update in the connection process.
