### ISSUE TITLE
Error in podcast make the application crash

### ISSUE THREAD

**Issue by clochix** [cozy-labs/konnectors#481]
Probably happening because a track in the podcast has no associated file.

``
/usr/local/cozy/apps/konnectors/node_modules/konnectors/build/server/konnectors/podcast.js:340
          throw _iteratorError4;
          ^

TypeError: Cannot read property '_id' of undefined
    at /usr/local/cozy/apps/konnectors/node_modules/konnectors/build/server/konnectors/podcast.js:114:55
    at /usr/local/cozy/apps/konnectors/node_modules/konnectors/node_modules/async/dist/async.js:3047:20
    at replenish (/usr/local/cozy/apps/konnectors/node_modules/konnectors/node_modules/async/dist/async.js:884:21)
    at iterateeCallback (/usr/local/cozy/apps/konnectors/node_modules/konnectors/node_modules/async/dist/async.js:869:21)
    at /usr/local/cozy/apps/konnectors/node_modules/konnectors/node_modules/async/dist/async.js:847:20
    at /usr/local/cozy/apps/konnectors/node_modules/konnectors/build/server/konnectors/podcast.js:119:14
    at /usr/local/cozy/apps/konnectors/node_modules/konnectors/build/server/konnectors/podcast.js:327:18
    at /usr/local/cozy/apps/konnectors/node_modules/konnectors/node_modules/cozydb/lib/model.js:213:18
    at /usr/local/cozy/apps/konnectors/node_modules/konnectors/node_modules/cozydb/lib/cozymodel.js:294:18
    at parseBody (/usr/local/cozy/apps/konnectors/node_modules/konnectors/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/konnectors/node_modules/konnectors/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

``

**Comment by ZeHiro** [comment]
@babolivier

**Comment by nicofrand** [comment]
« apparement le connecteur podcast plante sur « Débattre ! Réinventer la politique » de view-source:http://radiofrance-podcast.net/podcast09/rss_11919.xml »

**Comment by clochix** [comment]
@babolivier Zykino is hitting the same issue.

Couldn't we just, on https://github.com/cozy-labs/konnectors/blob/master/server/konnectors/podcast.js#L136 add a test: if episode.file then createTrackIfNotPresent else callback()

This issue is related to the content of the feed, so users will continue facing it on NextCozy.

**Comment by babolivier** [comment]
Sure, the test sounds like a good idea, so we exit the process if the file wasn't created. However, shouldn't we call callback() with an error so we can tell the user the retrieval wasn't successful for all of the episodes?

**Comment by clochix** [comment]
It looks like some entries inside feeds may not have attachments. I think this should trigger a warning, but not stop the import process by returning an error.
I don't know if it's possible to send a message to the user, explaining we have not been able to import some item, but without making the whole import fail.

**Comment by babolivier** [comment]
> It looks like some entries inside feeds may not have attachments. I think this should trigger a warning, but not stop the import process by returning an error.

You're right, I didn't think about this case.

> I don't know if it's possible to send a message to the user, explaining we have not been able to import some item, but without making the whole import fail.

Maybe send the user a notification? (I don't know if notifications are still a thing in the next version, couldn't take the time to update myself well enough)
