### ISSUE TITLE
Migrate server to plain JS (ECMAC 6?)

### ISSUE THREAD

**Issue by ZeHiro** [cozy-labs/konnectors#533]

**Comment by Phyks** [comment]
There should also be some lint strategy for the JS code I think, if Konnectors is to move to plain JS. Currently, only Coffee code is linted with coding style enforced.

**Comment by ZeHiro** [comment]
Hmm no. Js also has a linter eslint.

**Comment by Phyks** [comment]
Sure, I was thinking about eslint. And indeed, it is set up at the moment in Konnectors. Sorry for the noise, I got confused by the Travis build which stops on first error and only linted Coffee then :/

**Comment by ZeHiro** [comment]
No prob. :)

**Comment by Phyks** [comment]
Related to this, there seems to be an issue with ES6 and the dev tools:

```
$ coffee dev_tools.coffee --init
info - Konnector dev tool | Start initializing connectors...
Moment Timezone 0.5.3 was already loaded with data from 2016c
/Users/lverney/tmp/konnectors/server/konnectors/weboob/index.js:12
import moment from 'moment';
^^^^^^
SyntaxError: Unexpected token import
  at Object.exports.runInThisContext (vm.js:76:16)
  at Module._compile (module.js:528:28)
  at Object.Module._extensions..js (module.js:565:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at getKonnectorModules (/Users/lverney/tmp/konnectors/server/lib/konnector_hash.coffee:27:33)
  at Object.<anonymous> (/Users/lverney/tmp/konnectors/server/lib/konnector_hash.coffee:32:18)
  at Object.<anonymous> (/Users/lverney/tmp/konnectors/server/lib/konnector_hash.coffee:1:1)
  at Module._compile (module.js:556:32)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/lverney/tmp/konnectors/server/models/konnector.coffee:3:17)
  at Object.<anonymous> (/Users/lverney/tmp/konnectors/server/models/konnector.coffee:1:1)
  at Module._compile (module.js:556:32)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/lverney/tmp/konnectors/server/init/konnectors.coffee:8:13)
  at Object.<anonymous> (/Users/lverney/tmp/konnectors/server/init/konnectors.coffee:1:1)
  at Module._compile (module.js:556:32)
  at Object.loadFile (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (internal/module.js:20:19)
  at Object.init (/Users/lverney/tmp/konnectors/dev/connector.coffee:111:26)
  at Object.<anonymous> (/Users/lverney/tmp/konnectors/dev_tools.coffee:68:15)
  at Object.<anonymous> (/Users/lverney/tmp/konnectors/dev_tools.coffee:1:1)
  at Module._compile (module.js:556:32)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:162:23)
  at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:556:32)
  at Object.Module._extensions..js (module.js:565:10)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.runMain (module.js:590:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3
```

I tried to fix it, without success for the moment :/

**Comment by Phyks** [comment]
Issue mentionned above should be fixed in https://github.com/cozy-labs/konnectors/pull/560.

Fwiw, I used [Decaffeinate](https://github.com/decaffeinate/decaffeinate) while writing this PR and it gave really impressive results.
