### ISSUE TITLE
Dev tools

### ISSUE THREAD

**Issue by Phyks** [cozy-labs/konnectors#547]
Hi,

Just to sum up and centralize somewhere the status of dev tools and the documentation.
- [ ] [In the wiki](https://github.com/cozy-labs/konnectors/wiki/Use-the-dev-tools-to-make-the-development-easier) we should not use `freemobile` connector as it imports `PhoneBill` which is hardcoded in the module and does not allow the dev tools to show them. We should either use another konnector or fix `freemobile`.
- [x] Is there a way to reset the fields of a connector? (that is delete the accounts from the dev tools) `--reset` only purges models data I think.
- [x] Is it possible to `--init` multiple times (or is it conflict-prone?)?
- [x] In `coffee dev_tools.coffee --list`, I am not sure why there is an empty line, and no `vendor` listed.
- [x] There seems to be a problem with URL (or I did not find how to escape them):

```
$ coffee dev_tools.coffee --change weboob --fields weboobURL:http://localhost:8080/
info - Konnector dev tool | Changing fields for weboob with weboobURL:http://localhost:8080/.
Moment Timezone 0.5.3 was already loaded with data from 2016c
info - Konnector dev tool | Fields were successfully changed for weboob
Note: only fields described in the connector file are stored.

$ coffee dev_tools.coffee --status weboob
Moment Timezone 0.5.3 was already loaded with data from 2016c
[2016-10-26 14:45:31:296] warn - Fields variable undefined, use current one instead.
{ slug: 'weboob',
  accounts: [ { weboobURL: 'http' } ],
  fields: { weboobURL: 'text', JSONModulesDescription: 'text' },
  lastSuccess: undefined,
  lastImport: undefined,
  isImporting: false,
  importInterval: 'none',
  importErrorMessage: null }
*******************************************************************************
```

**Comment by Phyks** [comment]
Last point fixed in commit listed above.

**Comment by Phyks** [comment]
-[ ] Dev tools do not check that provided fields in a `--change` commands are indeed valid fields for this konnector.

**Comment by Phyks** [comment]
- [ ] Dev tools do not go to `build` folder to get Konnectors, then preventing from using ES6 syntax.

**Comment by Phyks** [comment]
https://github.com/cozy-labs/konnectors/pull/548/commits/167ba6712336774bd89d8b74e3e41970152ddb65 supports konnectors with ES6 syntax. I will put it in a separate PR.

**Comment by Phyks** [comment]
The list issue was that at some point I had a "null" Konnector created, due to some error most likely. It is no longer the case, and manually removing it from CouchDB solves the issue.

Vendor is simply not an attribute of the Konnector model, so no reason at all to list it there. This will also be in the upcoming separate PR.

**Comment by Phyks** [comment]
- [ ] Does a call to `--delete bill` delete both the `Bill` and the downloaded files?

**Comment by Phyks** [comment]
- [ ] 
```
$ coffee dev_tools.coffee --show file
/Users/lverney/tmp/konnectors/dev/data.coffee:69
        models.sort(function(a, b) {
              ^

TypeError: Cannot read property 'sort' of undefined
  at /Users/lverney/tmp/konnectors/dev/data.coffee:62:19
  at /Users/lverney/tmp/konnectors/node_modules/cozydb/lib/model.js:211:20
  at /Users/lverney/tmp/konnectors/node_modules/cozydb/lib/cozymodel.js:292:18
  at parseBody (/Users/lverney/tmp/konnectors/node_modules/request-json-light/main.js:75:10)
  at IncomingMessage.<anonymous> (/Users/lverney/tmp/konnectors/node_modules/request-json-light/main.js:109:14)
  at emitNone (events.js:91:20)
  at IncomingMessage.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:974:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```
