### ISSUE TITLE
Online konnector is broken

### ISSUE THREAD

**Issue by Phyks** [cozy-labs/konnectors#584]
Hi,

After upgrade to 0.7.4, it seems that Online konnector is heavily broken.

I have these messages in the log:

```
_http_outgoing.js:342
    throw new Error('`value` required in setHeader("' + name + '", value).');
    ^

Error: `value` required in setHeader("Content-Length", value).
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:342:11)
    at FormData.<anonymous> (/usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/request-json-light/node_modules/form-data/lib/form_data.js:344:13)
    at /usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/request-json-light/node_modules/form-data/lib/form_data.js:288:7
    at /usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/async/lib/async.js:726:13
    at /usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/async/lib/async.js:52:16
    at done (/usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/async/lib/async.js:241:17)
    at /usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/async/lib/async.js:44:16
    at /usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/async/lib/async.js:723:17
    at /usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/async/lib/async.js:167:37
    at /usr/local/cozy/apps/konnectors/node_modules/cozydb/node_modules/request-json-light/node_modules/form-data/lib/form_data.js:108:13
    at FSReqWrap.oncomplete (fs.js:82:15)
```

And a lot of
```
info - konnectors | File at https://console.online.net/fr/bill/show/ID downloaded.
{ [Error: ENOENT: no such file or directory, stat '/tmp/20150901_online_net.pdf']
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/tmp/20150901_online_net.pdf' }
```

**Comment by nicofrand** [comment]
Is it still broken, a PR was merged ?
